project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning: Decision Tree"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - text: GitHub
        href: https://github.com/BrightAmenyo/Heart_Disease-  

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual
